version: '2.4'

services:
  payroll_db:
    restart: always
    container_name: payroll-db
    image: postgres:11
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: wave
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  payroll_backend:
    restart: on-failure
    container_name: payroll-backend
    build:
      context: .
      dockerfile: DockerFile
    entrypoint: /entrypoint.sh
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    volumes:
      - .:/payroll
    depends_on:
      payroll_db:
        condition: service_healthy
